### ISSUE TITLE
REST API problem

### ISSUE THREAD

**Issue by gtulga** [Temasys/SkylinkJS#108]
Hi,

I'm going to create meeting room by REST API. But there is error:

Cannot POST /apirest/meetings/

I tried to "https://api.temasys.com.sg/rest/meetings/" URL. is this correct URL?

Thanks,

**Comment by ncurrier** [comment]
seems we have a configuration problem on our side, a fix will be deployed shortly in the meantime using https://api.temasys.com.sg/api/rest/meetings/ will bypass the problem

**Comment by gtulga** [comment]
Thanks. new URL working

**Comment by gtulga** [comment]
But new URL return "Your apiKey is not valid . Please go to developer.temasys.com.sg to manage your api keys.".

I already have app key on developer portal. What is issue?

Thanks,

**Comment by ncurrier** [comment]
a fix for the url error reported has been deployed. a member of our support team will contact you shortly to help resolve the invalid apiKey message.
