### ISSUE TITLE
Video resolution settings

### ISSUE THREAD

**Issue by serrynaimo** [Temasys/SkylinkJS#110]
I had some difficulty in figuring out how to use VIDEO_RESOLUTION (mostly because initially I head not really read the doc for joinRoom *cough*), but I I was thinking it'd be nice if the documentation for VIDEO_RESOLUTION, could have a link to "refer to joinRoom". Also some of the aspect ratio listed in VIDEO_RESOLUTION are wrong, for example QVGA is listed as width:320, height:180, but it should be 320:240. I haven't checked all resolution, but cursory glance indicates a few of the dimensions versus aspect ratios do not match. Do check.

**Comment by letchoo** [comment]
Hi @serrynaimo, thanks for pointing it out. We'll update these changes for the next release.

Most of our reference of VIDEO_RESOLUTION comes from here: http://en.wikipedia.org/wiki/Graphics_display_resolution#Video_Graphics_Array

**Comment by tienthanh8490** [comment]
Fixed
