### ISSUE TITLE
How to allow a user to be in more than one chat room

### ISSUE THREAD

**Issue by padre629** [Temasys/SkylinkJS#151]
Hi all. I'm using SkylinkJS 0.6.2 version, I want that a user can belong to two or more chat rooms at the same time. I don't know how to achieve this. 
What to do??

Thanks ;)

**Comment by tienthanh8490** [comment]
Hi @padre629 , right now SkylinkJS does not support that multi-room feature, but it's actually in our plan and we will try to make it available soon. Thanks for your interest and do keep an eye on your future releases.
