### ISSUE TITLE
Skylink getUserMedia throwing errors instead of using error callbacks

### ISSUE THREAD

**Issue by MichaelJCole** [Temasys/SkylinkJS#152]
Hey, I'm using `getUserMedia()` to get the screen.

Unless I'm misunderstanding, I noticed the Skylink code is throwing exceptions, instead of using the callbacks.  This means [my error callbacks are not happening] (http://ruben.verborgh.org/blog/2012/12/31/asynchronous-error-handling-in-javascript/) which is a bummer.

Here's an excerpt from `skylink.complete.js`:
```
            delete updatedConstraints.video.mediaSource;

            baseGetUserMedia(updatedConstraints, successCb, failureCb);

          } else {
            if (error === 'permission-denied') {
              throw new Error('Permission denied for screen retrieval');
            } else {
              throw new Error('Failed retrieving selected screen');
            }
          }
        };
```

Based on what I've learned about [async error handling] (http://ruben.verborgh.org/blog/2012/12/31/asynchronous-error-handling-in-javascript/), **those thrown errors cannot be caught**.  

I would expect more this behavior:
```
            delete updatedConstraints.video.mediaSource;

            baseGetUserMedia(updatedConstraints, successCb, failureCb);

          } else {
            if (error === 'permission-denied') {
              failureCb('Permission denied for screen retrieval');  // Use the callback, not an exception
            } else {
              failureCb('Failed retrieving selected screen');    // Use the callback, not an exception
            }
          }
        };
```

You could wrap the whole thing in a try{} catch(){}, but that gets tricky.  If I'm misunderstanding please let me know.  Here's my use case that isn't working:

```
  getScreen: function() {
console.log('getScreen');
    Helpers.connectForm.state.set('checkedScreen', true);

    navigator.getUserMedia({video: {mediaSource: 'window'}}, function(stream) {
console.log(screen);
      var vid = document.getElementById('browserCheck');
      attachMediaStream(vid, stream);
      Helpers.connectForm.state.set('canScreen', true);
    }, function(error) {
console.log(error);
      // Note: this is not being called for permission denied.  FIXME.
      Helpers.connectForm.state.set('canScreen', false);
    });
  },
```

The function is intended to check if the user can share the screen.  If so, attach it to browserCheck video.

Otherwise, set some state so the form can react.  Somewhere else shows the user a message based on the state of `checkedScreen` an `canScreen`

In the console I see:
```
getScreen
>
```

In Chrome, the share dialog comes up, I share the screen, but neither of my callbacks get called `function(stream)` or `function(error)`

I am successfully getting mic and camera in another prior `navigator.getUserMedia()` call.  `getScreen()` is called from clicking a button.

How are you testing and catching these thrown exceptions?  Am I missing something?

Thanks for any help!

**Comment by MichaelJCole** [comment]
Tried this code but it doesn't work either.  The callback is never called.

```
  getScreen: function() {
    console.log(Helpers.connectForm.skylink.shareScreen);
    Helpers.connectForm.state.set('checkedScreen', true);
    Helpers.connectForm.skylink.shareScreen(function(error, success) {
      if (error){
        console.log(error);
      } else {
        console.log(success);
      }
    });
  },
```

I see the `shareScreen` function and can read it.

Stepping through the code, these breakpoints are never triggered:
```
  try {
    window.getUserMedia(settings, function (stream) {
      self.once('mediaAccessSuccess', function (stream) {  // breakpoint never triggered
        if (self._inRoom) {           // breakpoint never triggered
```

**Comment by ncurrier** [comment]
Our next update of AdapterJS should address this issue for the most part. I will update here when that has been published, should be out in the next few days.

**Comment by MichaelJCole** [comment]
Awesome!  Thanks!

**Comment by letchoo** [comment]
Added checks for `skylink.joinRoom(null);`. This should throw an error in the callback

https://github.com/Temasys/SkylinkJS/releases/tag/0.6.4

**Comment by letchoo** [comment]
Hi @MichaelJCole, I would like to check if the 0.6.4 release did fix the issue you have. Does it still occur for you?

**Comment by MichaelJCole** [comment]
Hey Leticia, thanks for checking in.  I switched to SimpleWebRTC with a Xirsys backend.

**Comment by letchoo** [comment]
Thanks for the response, we will be closing this ticket then.
