### ISSUE TITLE
[0.6.4] Not receiving an incomingStream event, but receiving a peerLeft with undefined content

### ISSUE THREAD

**Issue by janesconference** [Temasys/SkylinkJS#161]
Sometimes (30% of the times), this happens. The other party connects and sends a stream, but no incomingStream is received. But when the other party disconnects, I receive a peerLeft with undefined content. This happens equally with 0.6.3 and 0.6.4.

**Comment by letchoo** [comment]
Hi @janesconference,

Thanks for raising this issue. Are you using the Skylink Media Relay feature for this connection?

Is there a delay when you receive the other party disconnection, if so how long is it

**Comment by janesconference** [comment]
@letchoo, thanks for your answer.

> Are you using the Skylink Media Relay feature for this connection?

Yes.

> Is there a delay when you receive the other party disconnection, if so how long is it

No, it is immediate.

**Comment by janesconference** [comment]
Btw, this is happening everytime I try to connect two or more parties, today.

**Comment by letchoo** [comment]
Thank you @janesconference, we are investigating this issue and will keep you updated when we have the information

**Comment by janesconference** [comment]
@letchoo - this sporadically keeps happening even in 0.6.10

**Comment by letchoo** [comment]
Hi @janesconference, it might help to provide the Application Key and the room name. But however, this conversation is public and the details you are going to share might be better with a 1-1 support in our [support portal](http://support.temasys.com.sg)

**Comment by letchoo** [comment]
Hi @janesconference, are you still experiencing this issue?

**Comment by letchoo** [comment]
Hi @janesconference, I have not heard from you for awhile. Please feel free to re-open this ticket when needed. Thanks
