### ISSUE TITLE
Cannot see local video stream and further use SDK when audio device is disabled.

### ISSUE THREAD

**Issue by srikinfin** [Temasys/SkylinkJS#163]
Expected : Even when the audio device is disabled, If the video device(webcam) is enabled, User should be able to see the video feed.

Present : When the Audio device is disabled, Even thought the webcam is working, User is not able to join a session.

Environment : Windows 10 as a Standard user where microphone/Input device is disabled.
Google chrome, Version 46.0.2490.86 m

Error in console shown below

SkylinkJS - <<MediaStream>> Failed retrieving stream: Error: Expected audio tracks length with 1 and video tracks length with 1 but received audio tracks length with 0 and video tracks length with 1(…) skylink.complete.js:16279

**Comment by letchoo** [comment]
Hi @srikinfin, how are you joining the room?

**Comment by letchoo** [comment]
Hi @srikinfin, there are new updates in 0.6.6 release which may resolve your issue. I suggest that you use and test the 0.6.6 release.

**Comment by letchoo** [comment]
Hi @srikinfin, we will be closing this ticket for now as the release version with the fix in [`0.6.6`](https://github.com/Temasys/SkylinkJS/releases/tag/0.6.6) is `6` versions behind the current release version [`0.6.12`](https://github.com/Temasys/SkylinkJS/releases/tag/0.6.12).

Feel free to re-open this ticket when there is still any existing issues.
