### ISSUE TITLE
Chrome <--> Firefox audio calling broken

### ISSUE THREAD

**Issue by joshdickson40** [Temasys/SkylinkJS#174]
Firefox 42, 43. Chrome 47. On Mac OS (latest), the Chrome client gets either a bad stream or a stream with no data - i.e. the user in Firefox can hear the Chrome side of the call, the Chrome user can not hear the Firefox user. Repeatable here on several different machines with Media Relay turned on and off.

Gist with debug active where the above is the result:
https://gist.github.com/joshdickson40/0cae708a133a6b6a9405

Note that this is fixed by requesting audio: true AND video: true when doing the init, but when video is false the stream does not work

**Comment by letchoo** [comment]
Hi @joshdickson40, this is a raised issue on chrome's end. You can follow up the ticket [here](https://code.google.com/p/chromium/issues/detail?id=534859), and it seems like they are releasing this fix in Chrome 49. Please do keep updated.

Note that it isn't Firefox's issue as noted in [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1215073).

**Comment by joshdickson40** [comment]
Got it, looked for an issue there and missed it - apologies. Will be a while before Chrome 49 makes it to stable, will update then. Thanks.

**Comment by letchoo** [comment]
Hi @joshdickson40, just wanted to update you that the fix is in the current Chrome 48. It should work now
