### ISSUE TITLE
[Bower] Incorrect dependency in 0.6.7 - socket.io client

### ISSUE THREAD

**Issue by janesconference** [Temasys/SkylinkJS#190]
Trying to install Skylinkjs 0.6.7 with bower, I see this error:

bower skylinkjs#~0.6.7          cached git://github.com/Temasys/SkylinkJS.git#0.6.7
bower skylinkjs#~0.6.7        validate 0.6.7 against git://github.com/Temasys/SkylinkJS.git#~0.6.7
bower sio-client#1.3.7      not-cached git://github.com/shSina/socket.io-client.git#1.3.7
bower sio-client#1.3.7         resolve git://github.com/shSina/socket.io-client.git#1.3.7
bower sio-client#1.3.7    ENORESTARGET No tag found that was able to satisfy 1.3.7

Looking at the socket.io-client bower repo, there's no 1.3.7 release, latest is 1.3.6: https://github.com/shSina/socket.io-client/releases

Could you please fix the dependency so bower users can use 0.6.7?

Thanks.

**Comment by ncurrier** [comment]
thanks for reporting this issue.

**Comment by janesconference** [comment]
I think the error is here: https://github.com/Temasys/SkylinkJS/blob/master/bower.json#L28

Please tell me we don't have to wait for 0.6.8 to see the fix :/

**Comment by ncurrier** [comment]
We will be releasing a 0.6.8 release to address this issue on Monday morning Singapore time. This will have to go through our internal release process to make this happen and validate, we as a rule do not release during non-office hours unless it is a critical issue, apologies for the delay.

**Comment by janesconference** [comment]
Btw I contacted the mantainer of the socket.io-client repo, it seems he's adding all the socket.io releases.

**Comment by ncurrier** [comment]
awesome, thanks.

**Comment by letchoo** [comment]
Hi @janesconference,

This is fixed in the release ver 0.6.8.

**Comment by janesconference** [comment]
thanks!
