### ISSUE TITLE
0.6.9 , re connection is not working well

### ISSUE THREAD

**Issue by edushare** [Temasys/SkylinkJS#197]
0.6.4 do not have same issue.

this issue cause when user switch to share screen, the other party not able to see the changes.

**Comment by letchoo** [comment]
Hi @edushare,

I would like to know how are you implementing the screensharing changes.

**Comment by edushare** [comment]
the call is direct called
Demo.Skylink.shareScreen();

when I trace the problem , I found the re-connect event is not triggered at all. 

I test manually but following function,

Demo.Skylink._restartPeerConnection(peerId, true);

the restart is not trigger as well.

**Comment by letchoo** [comment]
Hi @edushare,

I'll require information how you are implementing it.

Are you by any chance relying on the peerRestart event or shareScreen() callback?

**Comment by edushare** [comment]
you can simply check if the Demo.Skylink._restartPeerConnection(peerId, true) really cause restart happen.

The root cause is not come from screen sharing.

**Comment by letchoo** [comment]
Does this issue occurs for 0.6.7?

**Comment by edushare** [comment]
did not test it

**Comment by letchoo** [comment]
Hi @edushare,

I've tried `Demo.Skylink._restartPeerConnection(peerId, true);` and it works for me. I'm using `0.6.9` version. I would like to know how you are implementing it that would cause the issue.

**Comment by letchoo** [comment]
Hi @edushare,

Just to catch up with you a bit. It may be useful to provide the logs and screenshots, and the code how we are retrieving the stream as to resolve your issue that you are facing.

**Comment by letchoo** [comment]
Hi @edushare, just to catch up a bit. Does this issue occurs for you still in the current release version `0.6.12`?

**Comment by letchoo** [comment]
Hi @edushare, I'm not getting any response from you here. Will be closing this ticket temporarily
