### ISSUE TITLE
[0.6.7]: shareScreen() callback is not triggered

### ISSUE THREAD

**Issue by letchoo** [Temasys/SkylinkJS#198]
Noticed bug was that when users are in the room, the `shareScreen()` callback is not triggered.

This could be due to the issue as pointed in this part of the code https://github.com/Temasys/SkylinkJS/blob/master/source/stream-media.js#L2246

**Comment by letchoo** [comment]
This would be resolved in 0.6.10

**Comment by edushare** [comment]
any update on this issue?

**Comment by letchoo** [comment]
Hi @edushare, this fixes are in our timeline however I cannot give a fixed date when this will happen as we are currently busy with other priorities. Meanwhile, a suggestion is to use the [`mediaAccessSuccess` event](http://cdn.temasys.com.sg/skylink/skylinkjs/latest/doc/classes/Skylink.html#event_MediaAccessSuccess] for the `success` callback (see the `isScreensharing` flag) and the [`mediaAccessError` event](http://cdn.temasys.com.sg/skylink/skylinkjs/latest/doc/classes/Skylink.html#event_mediaAccessError) for the `error` callback (see the `isScreensharing` flag). Sorry for the inconvenience

**Comment by JanNorden** [comment]
The same issue seems to exist with sendStream().

**Comment by letchoo** [comment]
Hi @JanNorden, thanks for pointing it out. For now as a workaround, the same solution provided above would work.

**Comment by oooookk7** [comment]
Resolved in [0.6.15 release](https://github.com/Temasys/SkylinkJS/releases/tag/0.6.15).
