### ISSUE TITLE
getPeers not working

### ISSUE THREAD

**Issue by 11111000000** [Temasys/SkylinkJS#200]
```javascript
skylink
      .getPeers(true,
                ((error, success) =>
                 console.log('getPeers', error,success)))

```
, used after success `skylink.init`, never call it's callback and no any `getPeersStateChange` triggered.
But `peerJoined` works as expected. So, I syncronize list of peers through  counting of `peerJoined`, `peerLeft` events.

**Comment by tienthanh8490** [comment]
Hi @11111000000 , note that [getPeers](http://cdn.temasys.com.sg/skylink/skylinkjs/latest/doc/classes/Skylink.html#method_getPeers) only works when you're using a privileged alias key. Have you verified that the alias key you're using has privileged feature enabled ?

**Comment by udit7590** [comment]
Getting the same issue. Yes I have verified that I am using privileged key and still getting the error

**Comment by tienthanh8490** [comment]
Hi @udit7590, may I know your username and the name of the key you're using ?

**Comment by udit7590** [comment]
@tienthanh8490  Username: `uditvinsol`, API key name:  `alias-Privileged`

**Comment by tienthanh8490** [comment]
Hi @udit7590 , I tested using your key and was able to get the list of other peers with getPeers().

Note that from the [document](http://cdn.temasys.com.sg/skylink/skylinkjs/latest/doc/classes/Skylink.html#method_getPeers) , if you don't set the parameter showAll=true, getPeers() will only provide the list of unprivileged peers (autoIntroduce = isPrivileged = false). I also noticed that you haven't created any unprivileged alias key, so if you run getPeers() without any parameter you won't be able to get anything in your case.

Could you try with getPeers(true) and let me know the result ?

**Comment by letchoo** [comment]
Hi @11111000000 and @udit7590, hadn't heard from you for awhile on this issue. Please feel free to open a [support ticket here](http://support.temasys.com.sg) if there are any issues. I'm closing this ticket for now.
