### ISSUE TITLE
Typescript Typing File

### ISSUE THREAD

**Issue by naveensky** [Temasys/SkylinkJS#205]
Hi,

I am wondering if we have a typescript typings file available for easy consumption with typescript ? It will be really helpful for developers like me to get started

You can read more info at https://github.com/typings/typings

In case I could be of any help developing this, please let me know.

**Comment by letchoo** [comment]
Hi @naveensky, our project currently have other priorities as of the moment. But feel free to PR any new feature - like for instance typescript typings file (we will gladly accept it - `0.6.x-development` branch).

If this blocks you from developing anything, we will review it.

For now, we will look into it when we have time.

**Comment by naveensky** [comment]
Sure, if I get to a point of creating typescript file for this, I will send a PR definitely. Thanks for your response.

**Comment by letchoo** [comment]
Thanks @naveensky! It is appreciated.
