### ISSUE TITLE
Documentation not up to date with API

### ISSUE THREAD

**Issue by MvnTruong** [Temasys/SkylinkJS#208]
Back in 2014 the API for the incomingStream event has changed, as per this pull request:
https://github.com/Temasys/SkylinkJS/pull/35

However, the documentation still doesn't reflect the payload change, i.e. it still lists isSelf as the fourth parameter:
http://cdn.temasys.com.sg/skylink/skylinkjs/latest/doc/classes/Skylink.html#event_incomingStream
http://cdn.temasys.com.sg/skylink/skylinkjs/latest/doc/classes/Skylink.html#constructor

**Comment by letchoo** [comment]
@MvnTruong thanks for pointing out. We will revise this in our next release version.

**Comment by letchoo** [comment]
@MvnTruong thanks for pointing out and this fixes is released in 0.6.11.

https://github.com/Temasys/SkylinkJS/releases/tag/0.6.11
