### ISSUE TITLE
skylink.shareScreen not called if scare succedes

### ISSUE THREAD

**Issue by JanNorden** [Temasys/SkylinkJS#224]
I have the following code:

```javascript
this.skylink.shareScreen(true, mediaOptions, (error: any, _success: any): void => {
    if (error) {
        console.log('Failed sharing screen', error);  // this is called if user declines share
    } else {
        console.log('sharing screen'); // this is never called
    }
```
As indicated by the comments the callback is called if the user declines the share. However, if the share succedes, it is never called.

**Comment by letchoo** [comment]
Hi @JanNorden, this is a known issue we are rectifying in next releases in #198. We will inform you when the fixes has been made. Meanwhile, while waiting for fixes, the alternative method is to use [`mediaAccessSuccess` event](http://cdn.temasys.com.sg/skylink/skylinkjs/latest/doc/classes/Skylink.html#event_mediaAccessSuccess) for the `success` callback (see the `isScreensharing` flag in event payload) and [`mediaAccessError` event](http://cdn.temasys.com.sg/skylink/skylinkjs/latest/doc/classes/Skylink.html#event_mediaAccessError) for the `error` callback (see the `isScreensharing` flag in the event payload).  If there is no more other issues, we will be closing this ticket as I'll be marking this as a duplicate.
