### ISSUE TITLE
Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by tomasz-nolberczak** [Temasys/SkylinkJS#225]
Hello guys,

I'm trying to write my app with SkylinkJS. While launching init() method at Skylink object, there's weird problem in Chrome console:

"Cannot read property 'error' of undefined". Here is my code (it is Meteor app):

`Template.myTemplate.onRendered(function() {
    require('skylinkjs');

    let self = this;

    self.skylink = null;

    const API_KEY = Meteor.settings.public.skylink;
    const ROOM_NAME = 'my-room-name';

    self.skylink = new Skylink();

    if (self.skylink) {
        // self.skylink.setLogLevel(4);
        // self.skylink.setLogLevel(self.skylink.LOG_LEVEL.LOG);

        self.skylink.on("incomingStream", function (peerId, stream, peerInfo, isSelf) {
            if (isSelf) {
                attachMediaStream(document.getElementById("selfVideo"), stream);
            } else {
                var peerVideo = document.createElement("video");

                peerVideo.id = peerId;
                peerVideo.autoplay = "autoplay";

                document.getElementById("peersVideo").appendChild(peerVideo);
                attachMediaStream(peerVideo, stream);
            }
        });

        self.skylink.on("peerLeft", function (peerId, peerInfo, isSelf) {
            if (!isSelf) {
                var peerVideo = document.getElementById(peerId);
                // do a check if peerVideo exists first
                if (peerVideo) {
                    document.getElementById("peersVideo").removeChild(peerVideo);
                } else {
                    console.error("Peer video for " + peerId + " is not found.");
                }
            }
        });

        self.skylink.on("readyStateChange", function (state, room) {
           console.log("Room (" + room + ") state: ", room);
        });

        self.skylink.init({
            appKey: API_KEY,
            apiKey: API_KEY,
        }, (e, s) => {
            if (e) console.log(e);
            else {
                console.log(s);
            }
        }); 
    }`

![screenshot_9](https://cloud.githubusercontent.com/assets/7458770/15290118/af4cec0c-1b76-11e6-9f55-8d2d6baeca2a.jpg)

Am I doing something wrong? I'm using newest version of library from NPM (https://www.npmjs.com/package/skylinkjs).

Thanks!

**Comment by letchoo** [comment]
Hi @tomasz-nolberczak, do you have a demo I can test to reproduce this issue?

**Comment by tomasz-nolberczak** [comment]
Hello @letchoo. I think that we resolved our problem. We used basic version of library from NPM instead of that coming from CDN. Using CDN script made it work. Thank you for your answer :) You can close the ticket.

**Comment by letchoo** [comment]
Alright :)
