### ISSUE TITLE
Skylink on bowser

### ISSUE THREAD

**Issue by pagoad** [Temasys/SkylinkJS#229]
Hi.
Skylink is amazing and we will be using it on our new project.
I have a question. Is it possible to mute audio stream on bowser(ios) browser.
Skylink work on it very well but I have problems with muting.
This function is just not working. Is it posiible to do something with that?

**Comment by letchoo** [comment]
Hi @pagoad, we currently do not explicitly support bowser browser.

See [the related open AdapterJS ticket](https://github.com/Temasys/AdapterJS/issues/43).

Is the muting audio stream issue from the bowser browser?

**Comment by pagoad** [comment]
Problem is that bowser do not have console or I have no idea hot to take logs from it.
Sound is good, working, but I need to make it work only when user pushing button and this is the issue.
I will try on Adappter

**Comment by letchoo** [comment]
@pagoad we will check in the future when we have time. Right now it is not in priority for the moment but feel free to contribute and PR for support.

**Comment by pagoad** [comment]
I hope will we get webrtc on iOS and it will solve the problem :)

**Comment by letchoo** [comment]
@pagoad would hopefully wait for it to happen. feel free to check out our [iOS SDK](http://skylink.io/ios) to utilise the Skylink Platform on iOS devices and thank you for using Skylink :)
