### ISSUE TITLE
Is there a function to detect browser support

### ISSUE THREAD

**Issue by pagoad** [Temasys/SkylinkJS#230]
How can I check is user browser is compatibile with skylink?

**Comment by letchoo** [comment]
Hi @pagoad, currently we do not have a check to see if the browser is compatible.

But however, you can reference the list of supported browsers and the versions from this list:

https://github.com/Temasys/SkylinkJS#supported-browsers

We inherited the browser detection from [AdapterJS](https://github.com/Temasys/AdapterJS) with `window` variables like `webrtcDetectedBrowser` and `webrtcDetectedVersion`.

Here are the list of types of browsers you can expect:

`webrtcDetectedBrowser` contains the browser name and is a `typeof "string"`.
Here are several types you can expect:

- `safari`: Safari browser (requires plugin)
- `IE`: IE browser (requires plugin)
- `chrome`: Chrome browser or webkit based browsers
- `firefox`: Firefox browser
- `opera`: Opera browser
- `blink`: Mostly related to the Android browser
- `edge`: Edge browser

`webrtcDetectedVersion` contains the version of the browser (without decimals) and is a `typeof "number"`

If the browser does not support WebRTC, naturally it will throw this error in [the `init()` error callback](https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#method_init) with the `error.errorCode` as [`NO_WEBRTC_SUPPORT `](https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#attr_READY_STATE_CHANGE_ERROR).

**Comment by pagoad** [comment]
On website I need to show user on start that he connect, or not before .init().
Maybe you could implement this function in future?

**Comment by letchoo** [comment]
We will consider implement this feature in the future releases since it might be a useful feature. For your case however, you can do the following:

```
AdapterJS.webRTCReady(function () {
  if (!window.RTCPeerConnection) {
     // Display error that user browsers is not supported
     return;
  }
 
  // Might change with different release versions
  switch (window.webrtcDetectedBrowser) {
    case 'chrome':
      if (window.webrtcDetectedBrowser < 45) {
          // Not officially supported chrome. Might break.
      }
      break;
   case 'firefox':
     if (window.webrtcDetectedBrowser < 40) {
        // Not officially supported firefox. Might break.
     }
     break;
   case 'opera':
     if (window.webrtcDetectedBrowser < 32) {
        // Not officially supported opera. Might break.
     }
     break;
   case 'IE':
     if (window.webrtcDetectedBrowser < 9) {
        // Not officially supported IE browser version. Might break.
     }
     break;
   case 'safari':
     if (window.webrtcDetectedBrowser < 7) {
        // Not officially supported safari browser version. Might break.
     }
     break;
   default:
     // Not officially supported browser. Might break.
  }
  
  // Display that user can join the room
});

**Comment by pagoad** [comment]
I love your support.
You rock! Thx :)

**Comment by letchoo** [comment]
Np. Hope it helps you :)

**Comment by letchoo** [comment]
Will be closing this ticket if there is no other issues

**Comment by pagoad** [comment]
Ok :)
