### ISSUE TITLE
Safari after refresh don't work.

### ISSUE THREAD

**Issue by jonasmedeiros** [Temasys/SkylinkJS#233]
Sometimes at Safari Browser the PeerJoined don't work, all others browser even explorer work great, only safari is getting this error.

There is no error at javascript, the only problem is that PeerJoined is not called, and no error is called at the events that I have at the code that are, mediaAccessError, channelError and iceConnectionState is equal null the peerID.

Very strange problem, do you know what could be?

**Comment by letchoo** [comment]
Hi @gunsline2, do you have the demo app link which we can access and view?

**Comment by letchoo** [comment]
Hi @gunsline2 are you still experiencing this issue?

**Comment by geekavi** [comment]
close issue
