### ISSUE TITLE
Not able to join the room

### ISSUE THREAD

**Issue by amangupta26** [Temasys/SkylinkJS#237]
Not connecting to the signalling server. Following error is thrown:
<img width="1267" alt="screen shot 2016-06-09 at 3 37 39 pm" src="https://cloud.githubusercontent.com/assets/11567326/15926203/44365c10-2e58-11e6-9882-439fcf47783b.png">

**Comment by letchoo** [comment]
Hi @amangupta26, could you access this page https://signaling.temasys.com.sg?

**Comment by amangupta26** [comment]
Yup. But join room also started working. This issue we are seeing
intermittently.

**Comment by letchoo** [comment]
Hi @amangupta26, are you still experiencing this issue now?

**Comment by geekavi** [comment]
@amangupta26 closing issue as we did not get the response.
