### ISSUE TITLE
Using npm library generates warning about minified version

### ISSUE THREAD

**Issue by drujensen** [Temasys/SkylinkJS#240]
when I install the skylinkjs library using `npm install --save skylinkjs` and compile using webpack

I get this warning:
WARNING in ./~/skylinkjs/publish/skylink.complete.min.js
09:09:05 client.1 | Critical dependencies:
09:09:05 client.1 | 2:760-767 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.

**Comment by letchoo** [comment]
Hi @drujensen, thanks for pointing out. The case is that we are using the a bundled version as the `"main"` script in `package.json`. This might seem to be a Webpack specific issue [as noted in here](https://github.com/webpack/webpack/issues/1617). As noted in a comment posted by a user in the github issue link, there is a way to suppress the warnings that you receive [in here](https://github.com/webpack/webpack/issues/1617#issuecomment-223676403).

Currently, as we are having other prioritises right now, we will look into optimising our module with webpack in the future to prevent such warnings. Contributions are appreciated as PR to the `0.6.x-development` branch.

**Comment by drujensen** [comment]
thanks @letchoo.  I understand about priorities and will take a look at this if I get a chance.
