### ISSUE TITLE
Sound Input/Output problem

### ISSUE THREAD

**Issue by xvs32x** [Temasys/SkylinkJS#244]
Hello, we create confirence for 3-4 clients, but have sound bug:
Sometimes clients don't do not hear each other, for example if 2 people talk or noise at the same time, the sound of one of them is muffled. How can I solve this problem? Thanks :)

**Comment by letchoo** [comment]
Hi @xvs32x, are you using Chrome when connecting?

There is a related Chrome problem as discussed [in a group here](https://groups.google.com/forum/#!topic/discuss-webrtc/2R3M0y6Hezw).

This might not be something we can fix, but you maybe able to resolve it by playing around with the audio constraints. It seems like there was [a workaround fix in here that was raised as a Chrome bug](https://bugs.chromium.org/p/webrtc/issues/detail?id=4292):
```
audio: {
  mandatory: {
    { googEchoCancellation: false },
    { googEchoCancellation2: false }
  }
}
```
You may try and see if this helps.

**Comment by xvs32x** [comment]
@letchoo. thank you for help. I found solution based on your reply. I apllied this settings and sound work good:
`
 optional: [
                {googAutoGainControl: false},
                {googAutoGainControl2: false},
                {googEchoCancellation: true},
                {googEchoCancellation2:true},
                {googNoiseSuppression: false},
                {googNoiseSuppression2: false},
                {googHighpassFilter: false},
                {googTypingNoiseDetection: false},
                {googAudioMirroring: false}
            ]
`

**Comment by letchoo** [comment]
Hi @xvs32x, awesome! If that is so, I'll be closing this ticket since it's resolved and it's not a SkylinkJS issue. :)
