### ISSUE TITLE
[0.6.7]: sendStream() callback is not triggered

### ISSUE THREAD

**Issue by letchoo** [Temasys/SkylinkJS#246]
Similar to `shareScreen()` callback issue (#198), it is noticed that if there is no Peers in the Room and you pass in `getUserMedia()` constraints, the `callback` will not trigger.

For passing in MediaStream object, it is fine as you can see [this line here](https://github.com/Temasys/SkylinkJS/blob/0.6.14/source/stream-media.js#L798), but does not exists [in this line here](https://github.com/Temasys/SkylinkJS/blob/0.6.14/source/stream-media.js#L821).

Also, subscription of [`peerRestart` event](http://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#event_peerRestart) should only happen when User is in the Room and there is no Peers.

**Comment by oooookk7** [comment]
Resolved in [0.6.15](https://github.com/Temasys/SkylinkJS/releases/tag/0.6.15).
