### ISSUE TITLE
[0.6.x]: Deprecated methods like enableAudio() should not mute video tracks in Streams

### ISSUE THREAD

**Issue by letchoo** [Temasys/SkylinkJS#254]
**Issues faced:**
- Invoking `enableAudio()` results in `{ audioMuted: false, videoMuted: true }`
- Invoking `enableVideo()` results in `{ audioMuted: true, videoMuted: false }`
- Invoking `disableAudio()` results in `{ audioMuted: true, videoMuted: true }`
- Invoking `disableVideo()` results in `{ audioMuted: true, videoMuted: true }`

**Comment by oooookk7** [comment]
Resolved in [0.6.15](https://github.com/Temasys/SkylinkJS/releases/tag/0.6.15).
