### ISSUE TITLE
[0.6.1]: File transfers with Android / iOS SDK is broken

### ISSUE THREAD

**Issue by oooookk7** [Temasys/SkylinkJS#257]
It seems like there is problems with data transfer with Android and iOS SDK from the Web SDK. It could be due to the lack of simultaneous data-transfers support in Android and iOS SDK and the way we generate transferId.

**Comment by FieldSupport** [comment]
I am confused is this bug fixed? Does the iOS and Android need to be updated too?

**Comment by ncurrier** [comment]
This is not currently fixed, updates to the mobile SDKs will likely be needed to fully correct this issue. We are currently evaluating timing to get these releases out. It will not be in the currently scheduled mobile releases due this coming week however, will likely be present in the follow-up release expected in mid-November or earlier.

**Comment by oooookk7** [comment]
Resolved in [`0.6.16` release](https://github.com/Temasys/SkylinkJS/releases/tag/0.6.16) version.
