### ISSUE TITLE
Unable to create MCU enabled key

### ISSUE THREAD

**Issue by danishnazir** [Temasys/SkylinkJS#275]
Hello @letchoo i hope that you are doing great could you please help me in creating mcu enabled developer key? Is MCU feature available in free plan?
Regards,

**Comment by oooookk7** [comment]
Hi @danishnazir,

The MCU feature is not available on the free plan now but if you like to have MCU with free plan, please contact our sales team at sales@temasys.io.

**Comment by danishnazir** [comment]
Hi @letchoo 
Thanks for the information.

**Comment by oooookk7** [comment]
@danishnazir since the sales will be following up on this issue, I'll proceed to close this ticket.

**Comment by danishnazir** [comment]
Yeah sure thanks Sir @letchoo
