### ISSUE TITLE
One-To-Many Broadcast

### ISSUE THREAD

**Issue by kenanchristian** [Temasys/SkylinkJS#280]
What is the best way to do one-to-many video broadcast?
Is there any specific way to do this?

Or is it good enough to check the room first, if there's no people joined then get user media access will be fired. So the one that joined an existing room will not be requested for media access?

**Comment by oooookk7** [comment]
Hi @kenanchristian , to clarify with your usecase:

- The publisher will send but not receive any media from peers. Does the publisher necessarily need to know about other peers presence?
- The receiver will receive but not send any media.

Additionally, there is only one publisher in each room right?

**Comment by letchoo** [comment]
Additionally, there is only one publisher in each room right?

**Comment by kenanchristian** [comment]
Hey @letchoo thanks for the response :)
 1. The publisher needs to know about the presence
 2. Yes, maybe in the future the receiver will send data but not audio / video. Only messages 
 3. Yes, only one publisher in each room

**Comment by oooookk7** [comment]
Hi @kenanchristian, here's a recommended solution:

### Server-side
So there must be a way to distinguish the Publisher and Receiver. Either you can do a login account session to differentiate Publisher and Receiver, or a query URL at the page like `?publisher=0/1`. Before the Peer connects to the Room, the server may check if there is an existing Publisher already before setting the Peer as Publisher, and if there is an existing Publisher, set the Peer as Receiver, if not the update the flag in the DB and make the Peer become the Publisher.

### Client-side
So the client-side should have `joinRoom()` configuration passed in by the server-side, which is a JSON string (or a REST endpoint whichever is best for you) printed with different configuration:

- Publisher: `joinRoom({ audio: true, video: true, userData: xxxx })`
- Receiver: `joinRoom({ userData: xxxx })`

**Comment by oooookk7** [comment]
Additionally, if you are looking into a spectrum of about more than 5 Peers in a Room, I suggest you use the Skylink Media Relay (MCU) feature for your App Keys to reduce uploading bandwidth.

**Comment by kenanchristian** [comment]
It works! thanks for the fast reply 👍
