### ISSUE TITLE
black stream from IE (edge)

### ISSUE THREAD

**Issue by fix2015** [Temasys/SkylinkJS#289]
Hey guys, i have some trouble, when i use your product and try connect ie with chrome on diferent computer it send me stream with black screen,  i have no error in console nothing just black screen from interlocutor. Do you have bugs like this?

**Comment by fix2015** [comment]
i saw that for ie, incomingStream comes only once with "interlocutor" stream

**Comment by oooookk7** [comment]
Hi @fix2015, could you kindly open a ticket in [our support portal](http://support.temasys.com.sg) so we can proceed there with logs and other details. This is a public space so it might be inconvenient.
