### ISSUE TITLE
firefox can not get video, getarrom.io also not working on firefox

### ISSUE THREAD

**Issue by edushare** [Temasys/SkylinkJS#291]

**Comment by oooookk7** [comment]
Hi @edushare, what version of Firefox are you using?
Additionally, could you share the version of the SDK you are using?

**Comment by edushare** [comment]
54.0.1

**Comment by edushare** [comment]
should be the latest

**Comment by oooookk7** [comment]
Hi @edushare, could you go to [support.temasys.com.sg](https://support.temasys.com.sg) and open a ticket so we can proceed from there. We might require sensitive details like SDP logs etc.

**Comment by edushare** [comment]
you can just open getaroom.io and see it yourself

**Comment by oooookk7** [comment]
We have already tested on Firefox 54-55 without issues, and currently we do not have reported issues for Firefox browsers where the video is not working.

Please proceed to [support.temasys.com.sg](http://support.temasys.com.sg).

**Comment by edushare** [comment]
please close this ticket. issue solved.
