### ISSUE TITLE
error happened, cause connection can not be established

### ISSUE THREAD

**Issue by edushare** [Temasys/SkylinkJS#337]
![qq 20180910091327](https://user-images.githubusercontent.com/9190552/45271470-e81e4180-b4d9-11e8-884e-307b92ba1d74.png)

**Comment by edushare** [comment]
there should be a protection , if Datachanel is not available, message should be send through signaling

**Comment by iyharini** [comment]
Hi edushare, 

Thank you for your feedback.

The SDK provides public methods and events that you can use to handle this.

We would suggest listening to the DataChannelState Event (https://cdn.temasys.io/skylink/skylinkjs/latest/doc/classes/Skylink.html#event_dataChannelState).

If the state is not OPEN,  you can send the message via Signaling using the sendMessage method (https://cdn.temasys.io/skylink/skylinkjs/latest/doc/classes/Skylink.html#method_sendMessage).
