### ISSUE TITLE
what is the function call to adjust bandwidth

### ISSUE THREAD

**Issue by edushare** [Temasys/SkylinkJS#338]
https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/

Need a function for use to change bandwidth when he/she found quality is not good

**Comment by iyharini** [comment]
Hi edushare. You may wish to use the autoBandwidthAdjustment option under [joinRoom](https://cdn.temasys.io/skylink/skylinkjs/latest/doc/classes/Skylink.html#method_joinRoom)

**Comment by edushare** [comment]
anychance to change the bandwidth durring the call?

**Comment by iyharini** [comment]
Hi edushare. You can set the autoBandwidthAdjustment option to true when calling [joinRoom](https://cdn.temasys.io/skylink/skylinkjs/latest/doc/classes/Skylink.html#method_joinRoom)
