### ISSUE TITLE
No incomingStream Event to Other Caller when Switching Camera?

### ISSUE THREAD

**Issue by VikR0001** [Temasys/SkylinkJS#339]
When I use the new capability of switching cameras, the client's camera video feed is updated, but the other caller's video screen appears to go to black. There seems to be no `peerJoined` or `incomingStream` event on the other caller's client.

If I'm using the same browser e.g. Chrome for both callers, everything works perfectly. But if I use, e.g. Chrome for the first caller and Firefox for the second caller, the anomaly appears.

Here's a Codepen demo:

https://codepen.io/VikR/pen/jveejg

And here's a link to a video walkthrough of the Codepen demo:

https://www.dropbox.com/s/ph5969qmybuluet/Temasys_PeerJoined_Anomaly.mp4?dl=0

Thanks very much in advance for your support!

**Comment by iyharini** [comment]
Hi VikR0001,

We've made some changes to your code.
Please see the working demo here: https://temasys-cdn.s3.amazonaws.com/demos/ESS-1238/index.html

We'd recommend setting up a local server to test this instead of using codepen.
