### ISSUE TITLE
Temasys-Provided CodePen Skylink Demo Not Working on iPhone?

### ISSUE THREAD

**Issue by VikR0001** [Temasys/SkylinkJS#343]
I loaded the CodePen Skylink demo, provided by Temasys:

https://codepen.io/temasys/pen/GogabE

...on an iPhone/Safari and on a Mac desktop/Chrome, and joined the room from both.  The Mac Desktop showed the live video from both computers, but the iPhone showed black for both:

![img_2833](https://user-images.githubusercontent.com/10912958/45939654-1b0c0f00-bf89-11e8-9674-c3a3f5544568.jpg)

How can this be corrected?

**Comment by iyharini** [comment]
Hi VikR0001. Thank you for highlighting this to us. We have updated the demo on Codepen accordingly. This should work for you now.

**Comment by VikR0001** [comment]
Thanks very much!
