### ISSUE TITLE
Change audio source when screensharing

### ISSUE THREAD

**Issue by HemanthEverest** [Temasys/SkylinkJS#374]
Hi,

Is there any way i could change the audio source while sharing screen. I couldn't find a way by going through your documentation.

**Comment by paoloposadas** [comment]
Hi Hemanth,

You can use sendStream({ audio: { deviceId: xxx }, video: { deviceId: xxx } });

Do note that this method inherits options from getUserMedia(). You can read more about getUserMedia() on the link below.
https://cdn.temasys.com.sg/skylink/skylinkjs/latest/doc/classes/Skylink.html#method_getUserMedia
