### ISSUE TITLE
How do I check if a room if empty before joining?

### ISSUE THREAD

**Issue by amruthpillai** [Temasys/SkylinkJS#377]
Pretty self explanatory question. Is there a way I can check the number of the peers already in a room before actually having to join that room?

**Comment by iyharini** [comment]
Hi AmruthPillai. For reasons of security, Skylink is designed to not allow this without actually joining the room.
However, you may wish to consider joining the room with audio and video set to false and then use [getPeersInRoom](https://cdn.temasys.com.sg/skylink/skylinkjs/latest/doc/classes/Skylink.html#method_getPeersInRoom) to count the connected peers in the room.
