### ISSUE TITLE
Firefox Screen Share

### ISSUE THREAD

**Issue by felipecerutti** [Temasys/SkylinkJS#382]
I'm trying to use `skylink.shareScreen()` on Firefox and I'm getting a problem. Everything goes fine when I use the Google Chrome to share the screen, but when it goes to Firefox, the function starts and ask to select the screen and even show the screen on video for the person that is sharing the video, but the other participant gets a black video.

On console I'm getting the following error:

SkylinkJS [PfxWjc1uhYe9Tk4xAKgJ] - Failed adding local stream
Exception { name: "NS_ERROR_UNEXPECTED", message: "", result: 2147549183, filename: "https://app.nextwebinar.com.br/modules/frontend/shell/js/skylink.js", lineNumber: 22377, columnNumber: 0, data: null, stack: "Skylink.prototype._createPeerConnection/pc.removeStream@https://app.nextwebinar.com.br/modules/frontend/shell/js/skylink.js:22377:13\nupdateStreamFn/<@https://app.nextwebinar.com.br/modules/frontend/shell/js/skylink.js:32056:17\nupdateStreamFn@https://app.nextwebinar.com.br/modules/frontend/shell/js/skylink.js:32055:36\nSkylink.prototype._addLocalMediaStreams@https://app.nextwebinar.com.br/modules/frontend/shell/js/skylink.js:32085:11\nSkylink.prototype._doOffer@https://app.nextwebinar.com.br/modules/frontend/shell/js/skylink.js:23385:5\nSkylink.prototype._restartHandler@https://app.nextwebinar.com.br/modules/frontend/shell/js/skylink.js:29575:5\nSkylink.prototype._processSigMessage@https://app.nextwebinar.com.br/modules/frontend/shell/js/skylink.js:28742:5\nSkylink.prototype._createSocket/<@https://app.nextwebinar.com.br/modules/frontend/shell/js/skylink.js:28278:7\nr.prototype.emit@https://app.nextwebinar.com.br/cache/socket.io.js:6:13544\nr.prototype.onevent@https://app.nextwebinar.com.br/cache/socket.io.js:7:27805\nr.prototype.onpacket@https://app.nextwebinar.com.br/cache/socket.io.js:7:27424\nt.exports/<@https://app.nextwebinar.com.br/cache/socket.io.js:7:29601\nr.prototype.emit@https://app.nextwebinar.com.br/cache/socket.io.js:6:13544\nr.prototype.ondecoded@https://app.nextwebinar.com.br/cache/socket.io.js:6:19629\nt.exports/<@https://app.nextwebinar.com.br/cache/socket.io.js:7:29601\nr.prototype.emit@https://app.nextwebinar.com.br/cache/socket.io.js:6:13544\na.prototype.add@https://app.nextwebinar.com.br/cache/socket.io.js:6:11883\nr.prototype.ondata@https://app.nextwebinar.com.br/cache/socket.io.js:6:19574\nt.exports/<@https://app.nextwebinar.com.br/cache/socket.io.js:7:29601\nr.prototype.emit@https://app.nextwebinar.com.br/cache/socket.io.js:6:13544\nr.prototype.onPacket@https://app.nextwebinar.com.br/cache/socket.io.js:6:28772\nr.prototype.setTransport/<@https://app.nextwebinar.com.br/cache/socket.io.js:6:26387\nr.prototype.emit@https://app.nextwebinar.com.br/cache/socket.io.js:6:13544\nr.prototype.onPacket@https://app.nextwebinar.com.br/cache/socket.io.js:7:8690\nr.prototype.onData@https://app.nextwebinar.com.br/cache/socket.io.js:7:8639\nr.prototype.addEventListeners/this.ws.onmessage@https://app.nextwebinar.com.br/cache/socket.io.js:7:23620\n" }

**Comment by geekavi** [comment]
fixed issues in latest releases
