### ISSUE TITLE
Safari Screen Share Issue

### ISSUE THREAD

**Issue by felipecerutti** [Temasys/SkylinkJS#383]
I'm experiencing an issue using the function `skylink.shareScreen()` everything goes well using Google Chrome, but when I try to use Safari it just doesn't work. It keep showing the camera and even don't ask to allow screen sharing on the browser.

**Comment by rommel-temasys** [comment]
Hi @felipecerutti Safari does not support screensharing. You can read our article about Safari screensharing from this link. http://support.temasys.com.sg/solution/articles/12000035997-do-i-need-to-use-the-temasys-webrtc-plugin-with-safari-11-

**Comment by felipecerutti** [comment]
Thanks Rommel!
