### ISSUE TITLE
sendBlobData method not firing dataTransferState event in Safari

### ISSUE THREAD

**Issue by matteoredz** [Temasys/SkylinkJS#387]
Hi,

I'm using Skylink JS SDK (0.6.37) and when I try to send dome file (png, jpg, pdf...) using Safari (currently on 12, but experiencing the same issue on 11) the `dataTransferState` event is not fired so the file is not sent to other peers.

If 1 peer uses Chrome and the other Safari, the last one receives the file sent from Chrome but cannot open it (blob://.......)

Using 2 Chrome peers (latest version) I'm not experiencing any issue

**Comment by rommel-temasys** [comment]
Hi @matteoredz,

We have opened a ticket on our support portal to track this issue.  Ticket # 6133 and you have confirmed that this is already resolved.
