### ISSUE TITLE
skylink.stopRecording error when only one is streaming.

### ISSUE THREAD

**Issue by felipecerutti** [Temasys/SkylinkJS#388]
Hi Lads,

I'm having an issue and after loads of tests I have figured out that when you have a room where only one user is streaming audio/video, and the others are just the watchers, and you try to startRecord and then after a while you try to "stopRecording" you get an error 52, as below.

`SkylinkJS [MCU] - <<Recording>> (fd6bddf7-8a29-4f27-99fa-d7f1f17b42d0) Recording failure -> Error: Video/Audio from kH8ds_kBU-rBIty1AqUM1 is corrupted and can't be recorded. Error code: 52.`

If both are streaming audio and video, you do not get this error, I guess when other users join the room and you try to record, the MCU expects that both or all the users are streaming and when try to mix the audio/video gets this error.

I don't know if there is a way to only record a peer that is transmitting audio/video, I didn't find any information about it on documentation.

Hope someone got the same issue and could help me out.

Tnks

**Comment by geekavi** [comment]
New MCU is in Beta phase, which not only fixes issue like this but also provides full unified plan support.
