### ISSUE TITLE
Support for Chrome and Safari on IOS 

### ISSUE THREAD

**Issue by FieldSupport** [Temasys/SkylinkJS#409]
Still getting Webrtc not supported error message when using iOS Safari 11+ or Chrome has there been a formal release to include these browsers?
Thanks in advanced

**Comment by iyharini** [comment]
Hello. While iOS Chrome does not currently support WebRTC, you should be able to use SkylinkJS with iOS Safari 11/ the latest version of iOS Safari. In case of continuing issues with this, please do let us know. Thanks!
