### ISSUE TITLE
Does the code is really correct? why need to send target UserInfo to the peer?

### ISSUE THREAD

**Issue by edushare** [Temasys/SkylinkJS#447]
![image](https://user-images.githubusercontent.com/9190552/74016910-35a02600-49ce-11ea-9af3-b31f51fe3abf.png)

this code is so strange, why want to send peer info back to peer?

This will potentially cause issues.

**Comment by dinawee** [comment]
Hi, the message sent is not to a peer. It is part of our signalling server protocol.
