### ISSUE TITLE
Unhandle Rejection (Error) on leaveRoom

### ISSUE THREAD

**Issue by philipp-berger** [Temasys/SkylinkJS#456]
Hey,
I encountered an unhandled rejection error on upgrade to 2.1.
Scenario
Join room, without video and audio, so just as a spectator.
I directly call leaveRoom(roomName) and there the rejection comes :)

Stacktrace as Image :)
![image](https://user-images.githubusercontent.com/595887/78578495-e80a3300-782f-11ea-8db4-441f723e7545.png)

Proposed fix as patch
[patch.diff.txt](https://github.com/Temasys/SkylinkJS/files/4439480/patch.diff.txt)

**Comment by dinawee** [comment]
Hi @philipp-berger thanks for your comment. This is a known bug will be fixed in our next release.
