### ISSUE TITLE
0.5.7: When being kicked out from signaling server, the video connection is still connected

### ISSUE THREAD

**Issue by letchoo** [Temasys/SkylinkJS#93]
When I am being redirected and kicked from the signalling server, it seems like my video connection to other peers is still connected. This is a bug as the video connection should be disconnected.

**Comment by johache** [comment]
Not english, can’t figure out what you mean here...

> On 2 Mar 2015, at 7:59 am, Leticia Choo <notifications@github.com> wrote:
> 
> When I am redirected and kicked from the signaling server, it seems like my video connection to other peers is connection. This is a bug.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Temasys/SkylinkJS/issues/93>.
> 


--
Haché Jacques-Olivier
R&D Engineer at Temasys Communications Pte Ltd
Fr : +33 (0) 6 45 85 48 80
Sg : +65 9086 3673
