### ISSUE TITLE
0.5.7: In Safari, dataChannelState open is not fired despite DataChannel is available

### ISSUE THREAD

**Issue by letchoo** [Temasys/SkylinkJS#94]
There seems to be a bug that dataChannelState OPEN state does not fire in Safari. However when sending files, it seems to be working and able to transfer.

**Comment by agouaillard** [comment]
Is it safari or safari with the plugin. I suppose the later, in which case you should file a bug against the plugin as well, possibly mentioning this bug number in the description of the plugin bug so you can percolate the result when it s fixed on the plugin side.
 Cheers.

**Comment by letchoo** [comment]
Hi @agouaillard, tested and checked. This appears to be a SkylinkJS bug as I could find the DataChannel object with the readyState as open. It was fixed after realising that the DataChannel object received has a `typeof function` instead of `typeof object` in `ondatachannel` event object.

**Comment by agouaillard** [comment]
Ok.

Just to be thorough, is the type of the datachannelnobject in the corresponding event different between chrome, Firefox and the plugin?

If yes, and if this is a difference only with the plugin, I would ask Jo and s to why. If this NOT mandated by underlying plugin bindings and could be changed, I would advocate that the plugin object be of the same type.

Can you kindly check for me the object type differences?

**Comment by letchoo** [comment]
Hi @agouaillard,

I've tested cross-browsers. It seems only that Safari reflects the DataChannel object as a `typeof function` instead of `typeof object`. It's reflect also on IE as `typeof object` (plugin).

**Comment by johache** [comment]
> On 2 Mar 2015, at 8:05 am, Leticia Choo <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> There seems to be a bug that dataChannelState OPEN state does not fire in Safari. However when sending files, it seems to be working and able to transfer.
> 
> 

1. What is the name of the callback?
2. Do other states fire?
3. Does it work on IE?
4. Scenario? Test page? Anything…?

Seems like the plugin should fire
- onopen
-onclose
- onmessage

is it the case?


> —
> Reply to this email directly or view it on GitHub <https://github.com/Temasys/SkylinkJS/issues/94>.
> 


--
Haché Jacques-Olivier
R&D Engineer at Temasys Communications Pte Ltd
Fr : +33 (0) 6 45 85 48 80
Sg : +65 9086 3673

**Comment by letchoo** [comment]
@johache The RTCDataChannel methods does fires. It's just the way the RTCDataChannel object is interpreted as I discussed with you before, that Safari reads it as `typeof function` instead of `typeof object`. It's a SkylinkJS issue for this :)

**Comment by johache** [comment]
Interesting.
Again, if you see this issue popping at different places in the code, it might make sense for us to make a utility function in AdapterJS.

> On 3 Mar 2015, at 3:31 am, Leticia Choo <notifications@github.com> wrote:
> 
> @johache <https://github.com/johache> The RTCDataChannel methods does fires. It's just the way the RTCDataChannel object is interpreted as I discussed with you before, that Safari reads it as typeof function instead of typeof object. It's a SkylinkJS issue for this :)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Temasys/SkylinkJS/issues/94#issuecomment-76875606>.
> 


--
Haché Jacques-Olivier
R&D Engineer at Temasys Communications Pte Ltd
Fr : +33 (0) 6 45 85 48 80
Sg : +65 9086 3673
