### ISSUE TITLE
bower sio-client dependency does not exist

### ISSUE THREAD

**Issue by NikkiDreams** [Temasys/SkylinkJS#99]
"dependencies": {
    "adapterjs": "0.10.5",
    "sio-client": "1.2.1"
  }

1.3.3 or 1.3.2 are the only options 
This is keeping Bower from installing SkylinkJS even with --force

**Comment by serrynaimo** [comment]
Thanks @NikkiDreams ... Hope you don't mind using npm for the time being?

**Comment by NikkiDreams** [comment]
I am working around the issue for now. I wanted to include this as part of my bower.json due to the way my project is set up and built. npm does work fine. I actually have the SkylinkJS project cloned so I can be a little more intimate with the inner workings.
Cheers

**Comment by serrynaimo** [comment]
@NikkiDreams Just put the config up to sio-client 1.3.3 in bower.
